export enum EmailType {
  ORDER_CREATED = "ORDER_CREATED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  BANK_TRANSFER_INVOICE = "BANK_TRANSFER_INVOICE",
  INSTALLMENT_REMINDER = "INSTALLMENT_REMINDER",
  INSTALLMENT_OVERDUE = "INSTALLMENT_OVERDUE",
  ORDER_APPROVED = "ORDER_APPROVED",
  ORDER_REJECTED = "ORDER_REJECTED",
  PASSWORD_RESET = "PASSWORD_RESET",
  REFERRAL_BONUS_EARNED = "REFERRAL_BONUS_EARNED",
  REFERRAL_PAYOUT_REQUESTED = "REFERRAL_PAYOUT_REQUESTED",
  REFERRAL_PAYOUT_APPROVED = "REFERRAL_PAYOUT_APPROVED",
  STAFF_NEW_ORDER = "STAFF_NEW_ORDER",
  STAFF_PAYMENT_RECEIVED = "STAFF_PAYMENT_RECEIVED",
  STAFF_PENDING_PAYMENT = "STAFF_PENDING_PAYMENT"
}
