export enum EmailType {
  ORDER_CREATED = "ORDER_CREATED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  BANK_TRANSFER_INVOICE = "BANK_TRANSFER_INVOICE",
  INSTALLMENT_REMINDER = "INSTALLMENT_REMINDER",
  INSTALLMENT_OVERDUE = "INSTALLMENT_OVERDUE",
  ORDER_APPROVED = "ORDER_APPROVED",
  ORDER_REJECTED = "ORDER_REJECTED"
}