import { ReceiptRecord } from "./receipt.types";

const money = (amount: number) =>
  `NGN ${Number(amount).toLocaleString("en-NG", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2
  })}`;

/**
 * Lightweight dependency-free PDF generator for receipts.
 * Produces a clean A4 text/layout PDF suitable for download and email attachment.
 */
export const buildReceiptPdfBuffer = async (receipt: ReceiptRecord): Promise<Buffer> => {
  const lines: string[] = [];
  const company = receipt.company;

  const push = (text = "") => lines.push(text);

  push(company.name.toUpperCase());
  push(company.tagline);
  if (company.website) push(company.website.replace(/^https?:\/\//, ""));
  if (company.support_email) push(company.support_email);
  if (company.phone) push(company.phone);
  if (company.address) push(company.address);
  push("");
  push("OFFICIAL PAYMENT RECEIPT");
  push("========================================");
  push(`Receipt Number: ${receipt.receipt_number}`);
  push(`Invoice Number: ${receipt.invoice_number}`);
  push(`Payment Date: ${new Date(receipt.payment_date).toLocaleString("en-NG")}`);
  push(`Payment Method: ${receipt.payment_method}`);
  push(`Generated By: ${receipt.generated_by_name || "SYSTEM"}`);
  push("");
  push("CUSTOMER");
  push("----------------------------------------");
  push(`Name: ${receipt.customer_name || "Customer"}`);
  push(`Email: ${receipt.customer_email || "—"}`);
  push(`Phone: ${receipt.customer_phone || "—"}`);
  push("");
  push("ITEMS");
  push("----------------------------------------");

  for (const item of receipt.items) {
    push(`${item.product_name}`);
    push(`  Qty: ${item.quantity}  Unit: ${money(item.unit_price)}  Subtotal: ${money(item.subtotal)}`);
  }

  push("");
  push("PAYMENT SUMMARY");
  push("----------------------------------------");
  push(`Subtotal: ${money(receipt.subtotal)}`);
  push(`Discount: ${money(receipt.discount_amount)}`);
  push(`Delivery Fee: ${money(receipt.delivery_fee)}`);
  push(`Total Order Amount: ${money(receipt.order_total)}`);
  push(`Amount Paid: ${money(receipt.amount_paid)}`);
  push(`Outstanding Balance: ${money(receipt.remaining_balance)}`);
  push("");
  push("Thank you for shopping with Cbrixi.");
  push("Your trusted marketplace for smart devices.");
  push(`Support: ${company.support_email}`);

  return renderSimplePdf(lines);
};

const escapePdfText = (value: string) =>
  value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

const renderSimplePdf = (lines: string[]): Buffer => {
  const contentLines = [
    "BT",
    "/F1 11 Tf",
    "50 780 Td",
    "14 TL"
  ];

  lines.forEach((line, index) => {
    if (index === 0) {
      contentLines.push(`(${escapePdfText(line)}) Tj`);
    } else {
      contentLines.push("T*");
      contentLines.push(`(${escapePdfText(line)}) Tj`);
    }
  });

  contentLines.push("ET");
  const stream = contentLines.join("\n");
  const streamLength = Buffer.byteLength(stream, "utf8");

  const objects: string[] = [];
  objects.push("1 0 obj<< /Type /Catalog /Pages 2 0 R >>endobj");
  objects.push("2 0 obj<< /Type /Pages /Kids [3 0 R] /Count 1 >>endobj");
  objects.push(
    "3 0 obj<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>endobj"
  );
  objects.push(`4 0 obj<< /Length ${streamLength} >>stream\n${stream}\nendstream endobj`);
  objects.push("5 0 obj<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>endobj");

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];

  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${object}\n`;
  }

  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "utf8");
};
